# Generated by Django 5.0.4 on 2025-04-24 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MORNING', 'Morning (08:00-12:00 / S:09:00-12:00)'), ('AFTERNOON', 'Afternoon (13:00-17:00 / S:14:00-17:00)'), ('EVENING', 'Evening (18:00-22:00 / S:14:00-17:00)')], max_length=10, unique=True)),
                ('normal_start_time', models.TimeField()),
                ('normal_end_time', models.TimeField()),
                ('surgery_start_time', models.TimeField()),
                ('surgery_end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('room_type', models.CharField(choices=[('NORMAL', 'Normal Room'), ('SURGERY', 'Surgery Room')], default='NORMAL', max_length=10)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='clinics.clinic')),
            ],
            options={
                'unique_together': {('clinic', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='DutyRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='clinics.clinic')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.shift')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'shift')},
            },
        ),
    ]
