"""
Django settings for island_dental project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os # Often useful for joining paths, though Path is generally preferred now

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Consider loading this from an environment variable for production
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-xatomyfs*9i!uy&735fl!!riak)u$tyul&jqgukno)6m4rr%)w')

# SECURITY WARNING: don't run with debug turned on in production!
# Consider loading this from an environment variable
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Update this list with your domain name(s) when deploying
ALLOWED_HOSTS = []
# Example for deployment: ALLOWED_HOSTS = ['island-dental.example.com', 'www.island-dental.example.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Our apps 
    'users.apps.UsersConfig',
    'clinics.apps.ClinicsConfig',
    'appointments.apps.AppointmentsConfig',
    # Add any third-party apps later (e.g., 'crispy_forms', 'crispy_bootstrap5')
    # 'crispy_forms',
    # 'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'island_dental.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # MODIFIED: Add project-level templates directory
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True, # Still look inside app directories too
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'island_dental.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Using SQLite for development is fine. Switch to PostgreSQL or MySQL for production.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Consider changing this to your local timezone if needed for display logic
# TIME_ZONE = 'Indian/Maldives'
TIME_ZONE = 'UTC' # Keep as UTC for storing dates in DB is often recommended

USE_I18N = True

USE_TZ = True # Enable timezone support - Important!


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# ADDED: Define directory for project-wide static files
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ADDED: Location where collectstatic will gather files for deployment
# STATIC_ROOT = BASE_DIR / "staticfiles" # Uncomment and configure for production deployment


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Custom Settings ---

# Custom user model 
AUTH_USER_MODEL = 'users.CustomUser'

# ADDED: Login/Logout URLs
LOGIN_REDIRECT_URL = '/' # Redirect to homepage after successful login (can be changed e.g., to 'appointments:home')
LOGOUT_REDIRECT_URL = '/' # Redirect to homepage after logout
LOGIN_URL = 'login' # The name='login' defined in your accounts/auth URLs

# Optional: Settings for crispy-forms if you decide to use it
# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# CRISPY_TEMPLATE_PACK = "bootstrap5"

# Session settings (Defaults are usually fine)
# SESSION_COOKIE_AGE = 1209600  # 2 weeks, in seconds

# Email settings (Needed for password reset, etc. Configure for production)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' # Or console backend for testing
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Use this for development to print emails to console
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-email-password' # Use environment variables!
# DEFAULT_FROM_EMAIL = 'webmaster@island-dental.example.com'